### ISSUE TITLE
.jar file does not run under linux with java 22

### ISSUE THREAD

**Issue by DanielNerd** [gamma-02/NBT_to_CSV#1]
hi, I tried to run your program under a my linux system, but it refuses to work. this is the crash report i get when running `java -jar nbttocsv-1.1-SNAPSHOT.jar`
```
Jun 17, 2024 1:39:17 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @af32eb6'
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:253)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:263)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:290)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:162)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:651)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:671)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:275)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:290)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:162)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:651)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:671)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```
I am not a java developer, so I have 0 clue to why this is happening, java is supposed to be compatible under all operating systems, which leads me to believe the software uses a windows dependent command, or assume windows filesystem.
this could be a me only issue as I have not tested it on a different system, if you need more info feel free to ask, i'd love to help as much as I can, and thanks in advance!

**Comment by gamma-02** [comment]
Yeah, I think this is a JavaFX issue... I may be wrong but it should work if built from source on your machine. 

I got a similar issue with Macs while testing, and the current version was compiled on one and works fine, but...

I'll take a look, though!
